openapi: 3.0.0
info:
  title: First Lab API
  description: First Lab API
  contact:
    email: hiluminc@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-oas3
servers:
- url: /
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /:
    get:
      operationId: rootGET
      responses:
        "200":
          description: search results matching criteria
          content:
            text/plain:
              schema:
                type: string
                example: Hello HTTP GET
                x-content-type: text/plain
      x-swagger-router-controller: Default
  /hash:
    post:
      operationId: hashPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-swagger-router-controller: Default
components:
  schemas:
    body:
      type: object
      properties:
        data:
          type: string
    inline_response_200:
      type: object
      properties:
        hash:
          type: string
      example:
        hash: hash
